# Example configuration file for cc-tools (YAML format)
# Place this file in one of the following locations:
#   /etc/cc-tools/config.yaml
#   ~/.config/cc-tools/config.yaml
#   ./config.yaml

notifications:
  ntfy_topic: my-claude-notifications